# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import userfav_pb2 as userfav__pb2


class UserFavStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFavList = channel.unary_unary(
                '/UserFav/GetFavList',
                request_serializer=userfav__pb2.UserFavRequest.SerializeToString,
                response_deserializer=userfav__pb2.UserFavListResponse.FromString,
                )
        self.AddUserFav = channel.unary_unary(
                '/UserFav/AddUserFav',
                request_serializer=userfav__pb2.UserFavRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteUserFav = channel.unary_unary(
                '/UserFav/DeleteUserFav',
                request_serializer=userfav__pb2.UserFavRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetUserFavDetail = channel.unary_unary(
                '/UserFav/GetUserFavDetail',
                request_serializer=userfav__pb2.UserFavRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class UserFavServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFavList(self, request, context):
        """过滤收藏信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserFav(self, request, context):
        """添加留言
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserFav(self, request, context):
        """删除留言
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserFavDetail(self, request, context):
        """删除留言
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserFavServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFavList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFavList,
                    request_deserializer=userfav__pb2.UserFavRequest.FromString,
                    response_serializer=userfav__pb2.UserFavListResponse.SerializeToString,
            ),
            'AddUserFav': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserFav,
                    request_deserializer=userfav__pb2.UserFavRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteUserFav': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserFav,
                    request_deserializer=userfav__pb2.UserFavRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetUserFavDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserFavDetail,
                    request_deserializer=userfav__pb2.UserFavRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserFav', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserFav(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFavList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserFav/GetFavList',
            userfav__pb2.UserFavRequest.SerializeToString,
            userfav__pb2.UserFavListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUserFav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserFav/AddUserFav',
            userfav__pb2.UserFavRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUserFav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserFav/DeleteUserFav',
            userfav__pb2.UserFavRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserFavDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserFav/GetUserFavDetail',
            userfav__pb2.UserFavRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
